<?php
	/** @var TelegramExtension $this */
?>

<form action="<?= _url('extension', 'configure', 'e', urlencode($this->getName())) ?>" method="post" data-auto-leave-validation="1">
	<input type="hidden" name="_csrf" value="<?= FreshRSS_Auth::csrfToken() ?>" />

	<div class="form-group">
		<label class="group-name" for="bot_token"><?= _t('ext.telegram.bot_token') ?></label>
		<div class="group-controls">
			<input type="text" id="bot_token" name="bot_token" value="<?= htmlspecialchars($this->getBotToken(), ENT_COMPAT, 'UTF-8') ?>" placeholder="123456789:AA..." />
		</div>

		<label class="group-name" for="chat_id"><?= _t('ext.telegram.chat_id') ?></label>
		<div class="group-controls">
			<input type="text" id="chat_id" name="chat_id" value="<?= htmlspecialchars($this->getChatId(), ENT_COMPAT, 'UTF-8') ?>" placeholder="-1001234567890" />
			<p><small><?= _t('ext.telegram.help') ?></small></p>
		</div>

		<label class="group-name" for="disable_web_page_preview"><?= _t('ext.telegram.disable_web_page_preview') ?></label>
		<div class="group-controls">
			<label>
				<input type="checkbox" id="disable_web_page_preview" name="disable_web_page_preview" value="1" <?= $this->getDisableWebPagePreview() ? 'checked="checked"' : '' ?> />
				<?= _t('ext.telegram.disable_web_page_preview_label') ?>
			</label>
			<p><small><?= _t('ext.telegram.disable_web_page_preview_help') ?></small></p>
		</div>

		<label class="group-name" for="filter"><?= _t('ext.telegram.filter') ?></label>
		<div class="group-controls">
			<input type="text" id="filter" name="filter" value="<?= htmlspecialchars($this->getFilter(), ENT_COMPAT, 'UTF-8') ?>" placeholder="*" />
			<p><small><?= _t('ext.telegram.filter_help') ?></small></p>
		</div>

		<label class="group-name" for="exclude-filter"><?= _t('ext.telegram.exclude_filter') ?></label>
		<div class="group-controls">
			<input type="text" id="exclude-filter" name="exclude-filter" value="<?= htmlspecialchars($this->getExcludeFilter(), ENT_COMPAT, 'UTF-8') ?>" placeholder="" />
			<p><small><?= _t('ext.telegram.exclude_filter_help') ?></small></p>
		</div>
	</div>

	<div class="form-group form-actions">
		<div class="group-controls">
			<button type="submit" class="btn btn-important"><?= _t('gen.action.submit') ?></button>
			<button type="reset" class="btn"><?= _t('gen.action.cancel') ?></button>
		</div>
	</div>
</form>
